### ISSUE TITLE
Max Level Leviathan 

### ISSUE THREAD

**Issue by Criticp** [Water-and-Critic/KH3-Rando-GoA#65]
The Leviathan wil be max level from the start.

**Comment by WaterKH** [comment]
Same as the #60 issue fix, although we'll need to add an infinite reload to this Dive Gimmick so that it reloads that box for us to retrieve the crabs from (Although, it may not work since it may load a different umap. If that's the case, we can just attach the logic to the other dive gimmick on the different island to fully level up.)

One of these will need to be set consistently to false on load:
- gim_CA_divegim_01
- gim_CA_divegim_02
- gim_CA_divegim_03
- gim_CA_divegim_04

**Comment by WaterKH** [comment]
Critic pointed out this gameflow: gameflow_CA_specialship_powerup - This gives the black pearl, so just update the QoL Table and wording to unlock this
